version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      WEATHER_API_KEY: f6ff271832aab033ae9eb88b0e4b1f48
      PORT: 5000
      REDIS_PORT: 6379
      REDIS_HOST: redis
      NODE_ENV: production
    links:
      - redis

  redis:
    image: redis
